name = "Jalerkin"
uuid = "1719b3bc-7dca-41b2-aee3-2b553c138c1e"
authors = ["Rafa Rodríguez Galván <rafael.rodriguez@uca.es>"]
version = "0.1.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
